### ISSUE TITLE
Jitpack is weird

### ISSUE THREAD

**Issue by frqnny** [Linguardium/WanderingTradesmen#3]
**Describe the bug**
Include a pastebin to a ***minimal*** trader script that can reproduce this bug.

**Expected behavior**
The jitpack file doesn't exist, it looks like. 
Going to: 
https://jitpack.io/io/github/Linguardium/WanderingTradesmen/1.1.0/
only shows build.log
and going to
https://jitpack.io/io/github/Linguardium/WanderingTradesmen/1.1.0/build.log
Shows that a failed build happens, so is it not released or published to 1.1.0?

**Versions (BE SPECIFIC)**
 - Fabric Loader Version:0.8.2+build.194
 - Fabric API Version: 0.5.1+build.294-1.15
 - MC Version: 1.15.2
 - Wander Tradesmen Verison: 1.1.9

**Additional context**
I have to download it and then put it in a cache folder for it to work temporarily, but you might want to fix the jitpack.

**Comment by Linguardium** [comment]
yep, i'll drop the nullable notation

**Comment by Linguardium** [comment]
fixed in 1.1.1
