### ISSUE TITLE
Make a unique spawn egg so we can at least test the trades 

### ISSUE THREAD

**Issue by frqnny** [Linguardium/WanderingTradesmen#4]
**Is this in the scope of a wandering trader mod**
if so, keep going

**Describe the solution you'd like**
A spawn egg that allows you to spawn your unique tradesman so you know it works.

**Describe alternatives you've considered**
A command, but a spawn egg would be nicer.

**Comment by Linguardium** [comment]
I think i can do something. normally i just muck with the config in modmenu and set it to spawn 100% of the time at 1200 ticks (1 minute) intervals. 
gives 45 seconds of trader (unless trade window is open) and a new one spawns every minute.
a spawner would be good though

**Comment by Linguardium** [comment]
fixed in 4b62742
