### ISSUE TITLE
Nose Model is Cut off

### ISSUE THREAD

**Issue by frqnny** [Linguardium/WanderingTradesmen#5]
**Describe the bug**
Include a pastebin to a ***minimal*** trader script that can reproduce this bug.
*Any trader script*

**Expected behavior**
A nose should render but it is cut off. >:L

**Versions (BE SPECIFIC)**
minecraft_version=1.15.2
yarn_mappings=1.15.2+build.15
loader_version=0.8.2+build.194
trade man version = 1.1.1
fabric_version=0.7.1+build.301-1.15

**Additional context**
https://ibb.co/Wf9sW81

**Comment by Linguardium** [comment]
that is a custom nose and is intended to look that way.

**Comment by Linguardium** [comment]
~~if you want a config for a standard nose, let me know and i'll add one~~

nvm, i added one for the next release. just add `.oldNose(true)` to your trader generation (or set the setting in the config to change all of them)
wont work until new version is released though.

**Comment by Linguardium** [comment]
fixed in 4b62742
