### ISSUE TITLE
Reduce size of mod by removing jar-in-jar dependencies

### ISSUE THREAD

**Issue by frqnny** [Linguardium/WanderingTradesmen#6]
**Is this in the scope of a wandering trader mod**
if so, keep going

**Describe the solution you'd like**
Remove logo.png in your resources, as well as lighten up the jar by removing extra resources, and if you want I can move that taco_man texture and remove ur taco man js file too. Libs are supposed to be light, and having heavy textures that are 700kb like that logo.png can incredibly make jars that JiJ the lib heavier. 
**Describe alternatives you've considered**
Idk, would like to know what that logo.png is for

**Comment by frqnny** [comment]
Yeah, the WanderingTradesman jar is 800 kb, it could be 100kb if it didn't have it.
Sorry if I am being picky, but I just want to know why you have a random 700kb thing that duplicates my mod's size <3

**Comment by frqnny** [comment]
After extensive research, I have found that its ur libs that take so much space, not logo.png so I will close this issue.

**Comment by Linguardium** [comment]
looks to be about 800kb in libs alone. May move to removing the jar in jar and just linking them from the curse page and the wiki
down to 89kb without JiJ anything.  Cloth config is the largest, and is needed for modmenu integration. I marked both as recommended (but not required) and marked libcd and "auto config API updated" as required (external). 

I will update the wiki sometime after the weekend and put out a new jar. in the meantime, Tag 1.1.2 has been created and can be built against.
