### ISSUE TITLE
LAN Crash

### ISSUE THREAD

**Issue by frqnny** [Linguardium/WanderingTradesmen#7]
**Describe the bug**
Crashes in multiplayer. 
https://paste.gg/p/anonymous/6353d7d3dcc746179d6b2a114d756bf1

**Expected behavior**
Not crash?

**Versions (BE SPECIFIC)**
minecraft_version=1.15.2
yarn_mappings=1.15.2+build.15
loader_version=0.8.2+build.194

#Fabric api
fabric_version=0.7.1+build.301-1.15
tradesment_version=1.1.2

**Additional context**
Original bug report.
https://github.com/franiscoder/TacoCraft/issues/2

**Comment by Linguardium** [comment]
Did you reproduce this on 1.1.2? the posted report on TacoCraft's issue was 1.1.1 (cant read paste.gg right now, but will check it out tonight, and i believe the 1.1.2 tag was set right before the version bump accidentally :( )

**Comment by frqnny** [comment]
I have not, I will later!

**Comment by Linguardium** [comment]
let me know. I know there was a crash in earlier versions and I had to fix it in b3f6151
i may have missed something. Please also upload your tweaker script so i can attempt to reproduce.
Thanks

**Comment by frqnny** [comment]
Psst, I'd update the fabric.mod.json so that it says 1.1.2 or whatever version. 

And just tested it myself, with a server in dev and a client in dev, and then my main account all in the server and I did not crash.

**Comment by Linguardium** [comment]
30d8c97 already did :P

**Comment by frqnny** [comment]
Great! I'll close the issue.
